# Libraries

In [1]:
import pandas as pd
from pathlib import Path
from modules.utils import load_train, load_test, load_submission_example

# Dataset

In [2]:
df_train = load_train()
df_train.head()

                                     path         label
0     data/raw/train/0_Recyclable/R_1.jpg  0_Recyclable
1    data/raw/train/0_Recyclable/R_10.jpg  0_Recyclable
2   data/raw/train/0_Recyclable/R_100.jpg  0_Recyclable
3  data/raw/train/0_Recyclable/R_1000.jpg  0_Recyclable
4  data/raw/train/0_Recyclable/R_1001.jpg  0_Recyclable

In [3]:
df_test = load_test()
df_test.head()

                     path image_id
0     data/raw/test/1.jpg        1
1    data/raw/test/10.jpg       10
2   data/raw/test/100.jpg      100
3  data/raw/test/1000.jpg     1000
4  data/raw/test/1001.jpg     1001

In [4]:
df_sub = load_submission_example()
df_sub.head()

   id  predicted
0   1        NaN
1   2        NaN
2   3        NaN
3   4        NaN
4   5        NaN

# EDA